on:
  # Run on push to main branch
  push:
  # Dispatch if triggered using Github (website)
  workflow_dispatch:

jobs:
  build-docc:
    runs-on: macos-latest
    steps:
      - name: Build documentation
        uses: 0xWDG/build-documentation@main
        with:
          product: SimpleNetworking
          # temppath: tmpdocs
          # branch: docs
          iOS: false
